### ISSUE TITLE
Permit a saner structure for YAML files

### ISSUE THREAD

**Issue by ziotom78** [ziotom78/instrumentdb#16]
Currently the command `importyaml` requires that entities, quantities, and data files be specified in three different parts of the file:

```yaml
entities:
  - …

quantities:
  - …

data_files:
  - …
```

However, these three concepts are usually nested, according to the sequence `entity1→entity2→quantity→data_file`. As an alternative to the approach shown above (which should not be removed), the `importyaml` command should accept this structure as well:

```yaml
entities:
  - name: entity1
    - quantities:
      - name: quantity1
        data_files:
          - name: data_file1
```
